### ISSUE TITLE
ESP8266 returns busy p...

### ISSUE THREAD

**Issue by Szbuli** [MaJerle/esp-at-lib#56]
I am using F407 with ESP8266. I upgraded the firmware of the ESP8266 to latest version:

> AT version:1.6.2.0(Apr 13 2018 11:10:59)
> SDK version:2.2.1(6ab97e9)
> compile time:Jun  7 2018 19:34:26

The ESP8266 most of the time returns: 

> busy p...

If i put a few ms sleep in the `send_data` function the library keeps reseting the ESP8266.

If you need more messages between the F407 and the ESP8266 let me know.

**Comment by MaJerle** [comment]
Minimal AT version is 2.1.0.

**Comment by Szbuli** [comment]
I have installed ESP8266 NONOS SDK V2.2.1.

**Comment by MaJerle** [comment]
> I have installed ESP8266 NONOS SDK V2.2.1.

We are talking about AT version, not SDK version.

**Comment by Szbuli** [comment]
On the offical site the latest AT version which i could find is V1.7.2, released at 2020.01.20.

Could you help me where can i download a sufficient version?

**Comment by MaJerle** [comment]
https://www.espressif.com/en/products/hardware/esp8266ex/resources

Under At section.

**Comment by Szbuli** [comment]
I was using that page for downloading the firmware. The highest version's are 

> ESP8266 NonOS AT Bin V1.7.2 - 2020.01.20
> ESP8266 IDF AT Bin V2.0 - 2019.07.16

There are no versions that are higher than 2.0

**Comment by MaJerle** [comment]
2.0 is ok
