### ISSUE TITLE
Basic AT commands problem in esp_private.h

### ISSUE THREAD

**Issue by thisisausername-rgb** [MaJerle/esp-at-lib#58]
I try to get the RAM of the ESP32 using ESP_AT_LIB. I notice that a basic AT command "ESP_CMD_SYSRAM"in esp_private.h line 69 may help me, but i can't find anything about it in esp_int.c like others such as "ESP_CMD_GMR". Does it mean that I have to write my own code or I miss something?

**Comment by MaJerle** [comment]
Header file tries to contain all possible commands, but I didnt find it useful to actuakky implement to retrieve ram usage from ESP32.

In thus case manual work is necessary to send command and then interpret it properly.
