### ISSUE TITLE
Add custom AT command issue

### ISSUE THREAD

**Issue by thisisausername-rgb** [MaJerle/esp-at-lib#59]
The supplier of the board provides a custom AT command to read the ADC value of ESP32. How do I add it to esp_AT_lib and get its return value or is there any other example of adding a custom AT command?How many files do I need to change?

**Comment by MaJerle** [comment]
Library does not support sending custom AT commands directly. It must be implemented with commands and parser needs to be added.

**Comment by thisisausername-rgb** [comment]
I see, thanks.
